# Generated by Django 6.0.6 on 2026-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_music_data_alter_music_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='favouites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='saves_count',
            field=models.IntegerField(default=0),
        ),
    ]
